const express = require('express')
const router = express.Router()
const login = require('./router/login')
const common = require('./router/common')
const girls = require('./router/girl')
const spider = require('./router/spider')
login(router)
common(router)
girls(router)
spider(router)
module.exports = router
